### ISSUE TITLE
fix: type generic invokeOrgAgent test mock to restore gateway build

### ISSUE THREAD

**Issue by diogo2806** [diogo2806/t3-privacy-guard#210]
## Problem

The `t3n-gateway` Docker build still fails under strict TypeScript after #208 because one generic test mock remains implicitly typed.

## Affected implementation

- `t3n-gateway/src/agent/agent-session.test.ts`
  - test: `uses the stateless keyed transport for organization-owned t3n_key credentials`
  - mock: `invokeOrgAgent: async <T>(apiKey) => ...`

## Current behavior

The build fails at `RUN npm run build` with:

```text
src/agent/agent-session.test.ts(80,31): error TS7006: Parameter 'apiKey' implicitly has an 'any' type.
```

The previous correction typed `checkOrgAgentDelegation`, but line 80 is actually the generic `invokeOrgAgent` mock. Because the mock explicitly declares `<T>`, TypeScript does not contextually infer the `apiKey` parameter type in this form, so `noImplicitAny` rejects it.

## Expected behavior

`t3n-gateway` must compile with the repository's strict TypeScript configuration without weakening compiler settings or changing runtime behavior.

## Required change

In `t3n-gateway/src/agent/agent-session.test.ts`, change:

```ts
invokeOrgAgent: async <T>(apiKey) => {
```

to:

```ts
invokeOrgAgent: async <T>(apiKey: string) => {
```

Preserve all existing assertions, generic return behavior, organization-owned agent flow, credential redaction and production implementation.

## Why

This is the remaining compile blocker shown by the real Docker build. The correction is test-only and aligns the mock parameter with the production `invokeOrgAgent(apiKey: string, ...)` contract.

## Acceptance criteria

- `npm run build` no longer reports `TS7006` at `agent-session.test.ts:80`.
- No TypeScript compiler option is relaxed.
- No production runtime behavior changes.
- Existing tests and assertions remain intact.
- No frontend/API/documentation change is required because this is a test typing defect only.

## Tests

- `t3n-gateway` TypeScript build.
- Existing organization-owned agent transport test remains unchanged except for explicit parameter typing.

**Comment by diogo2806** [comment]
Correção iniciada na branch `fix/210-type-invoke-org-agent-mock`, criada diretamente da `main`. Escopo: corrigir exclusivamente o `TS7006` remanescente no mock genérico `invokeOrgAgent` em `t3n-gateway/src/agent/agent-session.test.ts`.
